pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                script {
                    checkout scm
                }
            }
        }
        stage('Build') {
            steps {
                dir('backend') {
                    withCredentials([file(credentialsId: 'APPLICATION_YML', variable: 'application_yml')]) {
                        sh 'cp $application_yml ./src/main/resources/application.yml'
                    }
                    withCredentials([file(credentialsId: 'FIREBASE_JSON', variable: 'firebase_json')]) {
                        sh 'cp ${firebase_json} ./src/main/resources/bbogle-c47b4-firebase-adminsdk-u0qbs-1b00a4d6f7.json'
                    }
                    sh 'chmod +x ./gradlew'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t bbogle-backend:latest ./backend'
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('backend') {
                    script {
                        sh 'docker-compose up -d'
                    }
                }
            }
        }
        stage('Remove old Image') {
            steps {
                script {
                    sh 'docker image prune -f'
                }
            }
        }
    }
    post {
        success {
            script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                mattermostSend (
                    color: 'good',
                    message: "**Build Success** \n _backend_ \n ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID} (${Author_Name})\n(<${env.BUILD_URL}|Details>)\n :white_check_mark: ",
                    endpoint: 'https://meeting.ssafy.com/hooks/tcx6yaicaffxufcujwc1qq8qsw',
                    channel: 'B102_Build'
                )
            }
        }
        failure {
            script {
                def Author_ID = sh(script: "git show -s --pretty=%an", returnStdout: true).trim()
                def Author_Name = sh(script: "git show -s --pretty=%ae", returnStdout: true).trim()
                mattermostSend (
                    color: 'danger',
                    message: "**Build Failed** \n _backend_ \n ${env.JOB_NAME} #${env.BUILD_NUMBER} by ${Author_ID} (${Author_Name})\n(<${env.BUILD_URL}/console|Details>)\n :no_entry_sign: ",
                    endpoint: 'https://meeting.ssafy.com/hooks/tcx6yaicaffxufcujwc1qq8qsw',
                    channel: 'B102_Build'
                )
            }
        }
    }
}
